In [2]:
print("Item Based Recommnedation System")

Item Based Recommnedation System


In [3]:
#from google.colab import drive
#drive.mount('/content/gdrive')

In [4]:
import pandas as pd
import numpy as np
import seaborn as sns

In [5]:
#df_org=pd.read_csv('/content/gdrive/MyDrive/MyCapstone (1)/data/sample30.csv')
df_org=pd.read_csv('data/sample30.csv')
df_org.shape

(30000, 15)

In [6]:
df = df_org[['id','reviews_username','reviews_rating']]

In [7]:
df.shape

(30000, 3)

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 3 columns):
 #   Column            Non-Null Count  Dtype 
---  ------            --------------  ----- 
 0   id                30000 non-null  object
 1   reviews_username  29937 non-null  object
 2   reviews_rating    30000 non-null  int64 
dtypes: int64(1), object(2)
memory usage: 703.2+ KB


In [9]:
df.head()

id reviews_username  reviews_rating
0  AV13O1A8GV-KLJ3akUyj           joshua               5
1  AV14LG0R-jtxr-f38QfS        dorothy w               5
2  AV14LG0R-jtxr-f38QfS        dorothy w               5
3  AV16khLE-jtxr-f38VFn          rebecca               1
4  AV16khLE-jtxr-f38VFn        walker557               1

In [10]:
df.id.nunique()

271

In [11]:
df.reviews_username.nunique()

24914

In [12]:
df_user = df.dropna()

In [13]:
df_user.shape

(29937, 3)

In [14]:
duplicate = df_user[df_user.duplicated(['reviews_username', 'id'])]
duplicate

id reviews_username  reviews_rating
2      AV14LG0R-jtxr-f38QfS        dorothy w               5
12     AV16khLE-jtxr-f38VFn          jds1992               1
44     AV1h6Gu0glJLPUi8IjA_             solo               4
79     AV1l8zRZvKc47QAVhnAv    mylifeinheels               3
90     AV1l8zRZvKc47QAVhnAv    mylifeinheels               3
...                     ...              ...             ...
29807  AVpfW8y_LJeJML437ySW         joycakes               5
29827  AVpfW8y_LJeJML437ySW          emily95               5
29841  AVpfW8y_LJeJML437ySW   brookieboo1994               5
29921  AVpfW8y_LJeJML437ySW     talmariejohn               5
29944  AVpfW8y_LJeJML437ySW          filo123               5

[2349 rows x 3 columns]

In [15]:
duplicate = df_user[df_user.duplicated()]
duplicate

id reviews_username  reviews_rating
2      AV14LG0R-jtxr-f38QfS        dorothy w               5
12     AV16khLE-jtxr-f38VFn          jds1992               1
44     AV1h6Gu0glJLPUi8IjA_             solo               4
79     AV1l8zRZvKc47QAVhnAv    mylifeinheels               3
90     AV1l8zRZvKc47QAVhnAv    mylifeinheels               3
...                     ...              ...             ...
29807  AVpfW8y_LJeJML437ySW         joycakes               5
29827  AVpfW8y_LJeJML437ySW          emily95               5
29841  AVpfW8y_LJeJML437ySW   brookieboo1994               5
29921  AVpfW8y_LJeJML437ySW     talmariejohn               5
29944  AVpfW8y_LJeJML437ySW          filo123               5

[2198 rows x 3 columns]

In [16]:
# Extract duplicate rows
df_user[(df_user['id']=='AV1YGDqsGV-KLJ3adc-O') & (df_user['reviews_username']=='laura')]        

id reviews_username  reviews_rating
695  AV1YGDqsGV-KLJ3adc-O            laura               1
746  AV1YGDqsGV-KLJ3adc-O            laura               2

In [17]:
# dropping ALL duplicate values
df_user.drop_duplicates(keep = 'first', inplace = True)

<ipython-input-17-25316b5d7dec>:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_user.drop_duplicates(keep = 'first', inplace = True)


In [18]:
df_user.shape

(27739, 3)

In [19]:
#Getting rows where same user provided different ratings for smae item.
duplicate = df_user[df_user.duplicated(['reviews_username', 'id'])]
duplicate

id reviews_username  reviews_rating
746    AV1YGDqsGV-KLJ3adc-O            laura               2
905    AV1YGDqsGV-KLJ3adc-O             suri               5
1705   AVpe31o71cnluZ0-YrSD            chris               5
1884   AVpe41TqilAPnD_xQH3d            steve               3
1922   AVpe41TqilAPnD_xQH3d            james               4
...                     ...              ...             ...
28150  AVpfRTh1ilAPnD_xYic2            dusty               5
28158  AVpfRTh1ilAPnD_xYic2             tony               5
28269  AVpfRTh1ilAPnD_xYic2   melbournesandy               5
28354  AVpfRTh1ilAPnD_xYic2         7.87E+11               5
28657  AVpftikC1cnluZ0-p31V          lzinzow               5

[151 rows x 3 columns]

In [20]:
#Taking mean of different ratings provided by user for same item
df2 = df_user.groupby(['id','reviews_username']).mean().reset_index()

In [21]:
df2[(df2['id']=='AV1YGDqsGV-KLJ3adc-O') & (df2['reviews_username']=='laura')]  

id reviews_username  reviews_rating
187  AV1YGDqsGV-KLJ3adc-O            laura             1.5

In [22]:
print(df2.shape)
df2.head()

(27588, 3)


id reviews_username  reviews_rating
0  AV13O1A8GV-KLJ3akUyj           joshua             5.0
1  AV14LG0R-jtxr-f38QfS        dorothy w             5.0
2  AV16khLE-jtxr-f38VFn           amanda             5.0
3  AV16khLE-jtxr-f38VFn         ashley a             5.0
4  AV16khLE-jtxr-f38VFn      beccagrl532             1.0

In [23]:
# After removing duplicates
print(df2.shape)
print(df2.reviews_username.nunique())
print(df2.id.nunique())


(27588, 3)
24914
271


In [24]:
# Pivot the train ratings' dataset into matrix format in which columns are items and the rows are user IDs.
df_pivot = df2.pivot(
    index='reviews_username',
    columns='id',
    values='reviews_rating'
).fillna(0)

df_pivot.head(10)

id                AV13O1A8GV-KLJ3akUyj  AV14LG0R-jtxr-f38QfS  \
reviews_username                                               
00dog3                             0.0                   0.0   
00sab00                            0.0                   0.0   
01impala                           0.0                   0.0   
02dakota                           0.0                   0.0   
02deuce                            0.0                   0.0   
0325home                           0.0                   0.0   
06stidriver                        0.0                   0.0   
08dallas                           0.0                   0.0   
09mommy11                          0.0                   0.0   
1.11E+24                           0.0                   0.0   

id                AV16khLE-jtxr-f38VFn  AV1YGDqsGV-KLJ3adc-O  \
reviews_username                                               
00dog3                             0.0                   0.0   
00sab00                            0.0                   0.0   
01impala                           0.0                   0.0   
02dakota                           0.0                   0.0   
02deuce                            0.0                   0.0   
0325home                           0.0                   0.0   
06stidriver                        0.0                   0.0   
08dallas                           0.0                   0.0   
09mommy11                          0.0                   0.0   
1.11E+24                           0.0                   0.0   

id                AV1YIch7GV-KLJ3addeG  AV1YlENIglJLPUi8IHsX  \
reviews_username                                               
00dog3                             0.0                   0.0   
00sab00                            0.0                   0.0   
01impala                           0.0                   0.0   
02dakota                           0.0                   0.0   
02deuce                            0.0                   0.0   
0325home                           0.0                   0.0   
06stidriver                        0.0                   0.0   
08dallas                           0.0                   0.0   
09mommy11                          0.0                   0.0   
1.11E+24                           0.0                   0.0   

id                AV1YmBrdGV-KLJ3adewb  AV1YmDL9vKc47QAVgr7_  \
reviews_username                                               
00dog3                             0.0                   0.0   
00sab00                            0.0                   0.0   
01impala                           0.0                   0.0   
02dakota                           0.0                   0.0   
02deuce                            0.0                   0.0   
0325home                           0.0                   0.0   
06stidriver                        0.0                   0.0   
08dallas                           0.0                   0.0   
09mommy11                          0.0                   0.0   
1.11E+24                           0.0                   0.0   

id                AV1Ymf_rglJLPUi8II2v  AV1Yn94nvKc47QAVgtst  ...  \
reviews_username                                              ...   
00dog3                             0.0                   0.0  ...   
00sab00                            0.0                   0.0  ...   
01impala                           0.0                   0.0  ...   
02dakota                           0.0                   0.0  ...   
02deuce                            0.0                   0.0  ...   
0325home                           0.0                   0.0  ...   
06stidriver                        0.0                   0.0  ...   
08dallas                           0.0                   0.0  ...   
09mommy11                          0.0                   0.0  ...   
1.11E+24                           0.0                   0.0  ...   

id                AVpfrfHF1cnluZ0-pRai  AVpfrgjFLJeJML43BvCc  \
reviews_username               

In [25]:
print(df_pivot.shape)

(24914, 271)


In [26]:
# Copy the train dataset into dummy_train
dummy_df = df2.copy()

In [27]:
# The items not rated by user is marked as 1 for prediction. 
dummy_df['reviews_rating'] = dummy_df['reviews_rating'].apply(lambda x: 0 if x>=1 else 1)

In [28]:
# Convert the dummy train dataset into matrix format.
dummy_df = dummy_df.pivot(
    index='reviews_username',
    columns='id',
    values='reviews_rating'
).fillna(1)

In [29]:
dummy_df.head()

id                AV13O1A8GV-KLJ3akUyj  AV14LG0R-jtxr-f38QfS  \
reviews_username                                               
00dog3                             1.0                   1.0   
00sab00                            1.0                   1.0   
01impala                           1.0                   1.0   
02dakota                           1.0                   1.0   
02deuce                            1.0                   1.0   

id                AV16khLE-jtxr-f38VFn  AV1YGDqsGV-KLJ3adc-O  \
reviews_username                                               
00dog3                             1.0                   1.0   
00sab00                            1.0                   1.0   
01impala                           1.0                   1.0   
02dakota                           1.0                   1.0   
02deuce                            1.0                   1.0   

id                AV1YIch7GV-KLJ3addeG  AV1YlENIglJLPUi8IHsX  \
reviews_username                                               
00dog3                             1.0                   1.0   
00sab00                            1.0                   1.0   
01impala                           1.0                   1.0   
02dakota                           1.0                   1.0   
02deuce                            1.0                   1.0   

id                AV1YmBrdGV-KLJ3adewb  AV1YmDL9vKc47QAVgr7_  \
reviews_username                                               
00dog3                             1.0                   1.0   
00sab00                            1.0                   1.0   
01impala                           1.0                   1.0   
02dakota                           1.0                   1.0   
02deuce                            1.0                   1.0   

id                AV1Ymf_rglJLPUi8II2v  AV1Yn94nvKc47QAVgtst  ...  \
reviews_username                                              ...   
00dog3                             1.0                   1.0  ...   
00sab00                            1.0                   1.0  ...   
01impala                           1.0                   1.0  ...   
02dakota                           1.0                   1.0  ...   
02deuce                            1.0                   1.0  ...   

id                AVpfrfHF1cnluZ0-pRai  AVpfrgjFLJeJML43BvCc  \
reviews_username                                               
00dog3                             1.0                   1.0   
00sab00                            1.0                   1.0   
01impala                           1.0                   1.0   
02dakota                           1.0                   1.0   
02deuce                            1.0                   1.0   

id                AVpfs0tUilAPnD_xgqN2  AVpfsQoeilAPnD_xgfx5  \
reviews_username                                               
00dog3                             1.0                   1.0   
00sab00                            1.0                   1.0   
01impala                           1.0                   1.0   
02dakota                           1.0                   1.0   
02deuce                            1.0                   1.0   

id                AVpfshNsLJeJML43CB8q  AVpfthSailAPnD_xg3ON  \
reviews_username                                               
00dog3                             1.0                   1.0   
00sab00                            1.0                   1.0   
01impala                           1.0                   1.0   
02dakota                           1.0                   1.0   
02deuce                            1.0                   1.0   

id                AVpftikC1cnluZ0-p31V  AVpftymALJeJML43CZ6y  \
reviews_username                                               
00dog3                             1.0                   1.0   
00sab00                            1.0                   1.0   
01impala                           1.0                   1.0   
02dakota                           1.0               

In [30]:
from sklearn.metrics.pairwise import pairwise_distances

## Using Item similarity


# Item Based Similarity

In [31]:
df_pivot = df2.pivot(
    index='reviews_username', columns='id', values='reviews_rating'
).T

df_pivot.head()

reviews_username      00dog3  00sab00  01impala  02dakota  02deuce  0325home  \
id                                                                             
AV13O1A8GV-KLJ3akUyj     NaN      NaN       NaN       NaN      NaN       NaN   
AV14LG0R-jtxr-f38QfS     NaN      NaN       NaN       NaN      NaN       NaN   
AV16khLE-jtxr-f38VFn     NaN      NaN       NaN       NaN      NaN       NaN   
AV1YGDqsGV-KLJ3adc-O     NaN      NaN       NaN       NaN      NaN       NaN   
AV1YIch7GV-KLJ3addeG     NaN      NaN       NaN       NaN      NaN       NaN   

reviews_username      06stidriver  08dallas  09mommy11  1.11E+24  ...  zt313  \
id                                                                ...          
AV13O1A8GV-KLJ3akUyj          NaN       NaN        NaN       NaN  ...    NaN   
AV14LG0R-jtxr-f38QfS          NaN       NaN        NaN       NaN  ...    NaN   
AV16khLE-jtxr-f38VFn          NaN       NaN        NaN       NaN  ...    NaN   
AV1YGDqsGV-KLJ3adc-O          NaN       NaN        NaN       NaN  ...    NaN   
AV1YIch7GV-KLJ3addeG          NaN       NaN        NaN       NaN  ...    NaN   

reviews_username      zubb  zulaa118  zuttle  zwithanx  zxcsdfd  zxjki  \
id                                                                       
AV13O1A8GV-KLJ3akUyj   NaN       NaN     NaN       NaN      NaN    NaN   
AV14LG0R-jtxr-f38QfS   NaN       NaN     NaN       NaN      NaN    NaN   
AV16khLE-jtxr-f38VFn   NaN       NaN     NaN       NaN      NaN    NaN   
AV1YGDqsGV-KLJ3adc-O   NaN       NaN     NaN       NaN      NaN    NaN   
AV1YIch7GV-KLJ3addeG   NaN       NaN     NaN       NaN      NaN    NaN   

reviews_username      zyiah4  zzdiane  zzz1127  
id                                              
AV13O1A8GV-KLJ3akUyj     NaN      NaN      NaN  
AV14LG0R-jtxr-f38QfS     NaN      NaN      NaN  
AV16khLE-jtxr-f38VFn     NaN      NaN      NaN  
AV1YGDqsGV-KLJ3adc-O     NaN      NaN      NaN  
AV1YIch7GV-KLJ3addeG     NaN      NaN      NaN  

[5 rows x 24914 columns]

Normalising the movie rating for each movie for using the Adujsted Cosine

In [32]:
mean = np.nanmean(df_pivot, axis=1)
df_subtracted = (df_pivot.T-mean).T

In [33]:
df_subtracted.head()

reviews_username      00dog3  00sab00  01impala  02dakota  02deuce  0325home  \
id                                                                             
AV13O1A8GV-KLJ3akUyj     NaN      NaN       NaN       NaN      NaN       NaN   
AV14LG0R-jtxr-f38QfS     NaN      NaN       NaN       NaN      NaN       NaN   
AV16khLE-jtxr-f38VFn     NaN      NaN       NaN       NaN      NaN       NaN   
AV1YGDqsGV-KLJ3adc-O     NaN      NaN       NaN       NaN      NaN       NaN   
AV1YIch7GV-KLJ3addeG     NaN      NaN       NaN       NaN      NaN       NaN   

reviews_username      06stidriver  08dallas  09mommy11  1.11E+24  ...  zt313  \
id                                                                ...          
AV13O1A8GV-KLJ3akUyj          NaN       NaN        NaN       NaN  ...    NaN   
AV14LG0R-jtxr-f38QfS          NaN       NaN        NaN       NaN  ...    NaN   
AV16khLE-jtxr-f38VFn          NaN       NaN        NaN       NaN  ...    NaN   
AV1YGDqsGV-KLJ3adc-O          NaN       NaN        NaN       NaN  ...    NaN   
AV1YIch7GV-KLJ3addeG          NaN       NaN        NaN       NaN  ...    NaN   

reviews_username      zubb  zulaa118  zuttle  zwithanx  zxcsdfd  zxjki  \
id                                                                       
AV13O1A8GV-KLJ3akUyj   NaN       NaN     NaN       NaN      NaN    NaN   
AV14LG0R-jtxr-f38QfS   NaN       NaN     NaN       NaN      NaN    NaN   
AV16khLE-jtxr-f38VFn   NaN       NaN     NaN       NaN      NaN    NaN   
AV1YGDqsGV-KLJ3adc-O   NaN       NaN     NaN       NaN      NaN    NaN   
AV1YIch7GV-KLJ3addeG   NaN       NaN     NaN       NaN      NaN    NaN   

reviews_username      zyiah4  zzdiane  zzz1127  
id                                              
AV13O1A8GV-KLJ3akUyj     NaN      NaN      NaN  
AV14LG0R-jtxr-f38QfS     NaN      NaN      NaN  
AV16khLE-jtxr-f38VFn     NaN      NaN      NaN  
AV1YGDqsGV-KLJ3adc-O     NaN      NaN      NaN  
AV1YIch7GV-KLJ3addeG     NaN      NaN      NaN  

[5 rows x 24914 columns]

Finding the cosine similarity using pairwise distances approach

In [34]:
from sklearn.metrics.pairwise import pairwise_distances

In [35]:
# Item Similarity Matrix
item_correlation = 1 - pairwise_distances(df_subtracted.fillna(0), metric='cosine')
item_correlation[np.isnan(item_correlation)] = 0
print(item_correlation)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 0. 1.]]


Filtering the correlation only for which the value is greater than 0. (Positively correlated)

In [36]:
item_correlation[item_correlation<0]=0
item_correlation

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

# Prediction - Item Item

In [37]:
item_predicted_ratings = np.dot((df_pivot.fillna(0).T),item_correlation)
item_predicted_ratings

array([[0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.0304546 ,
        0.        ],
       [0.        , 0.        , 0.00930396, ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.00498975],
       [0.        , 0.        , 0.        , ..., 0.        , 0.05075767,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.0039918 ]])

In [38]:
item_predicted_ratings.shape

(24914, 271)

In [39]:
dummy_df.shape

(24914, 271)

### Filtering the rating only for the items not rated by the user for recommendation


In [40]:
item_final_rating = np.multiply(item_predicted_ratings,dummy_df)
item_final_rating.head()

id                AV13O1A8GV-KLJ3akUyj  AV14LG0R-jtxr-f38QfS  \
reviews_username                                               
00dog3                             0.0                   0.0   
00sab00                            0.0                   0.0   
01impala                           0.0                   0.0   
02dakota                           0.0                   0.0   
02deuce                            0.0                   0.0   

id                AV16khLE-jtxr-f38VFn  AV1YGDqsGV-KLJ3adc-O  \
reviews_username                                               
00dog3                        0.000000              0.013946   
00sab00                       0.000000              0.000622   
01impala                      0.009304              0.000000   
02dakota                      0.015507              0.000000   
02deuce                       0.012405              0.000000   

id                AV1YIch7GV-KLJ3addeG  AV1YlENIglJLPUi8IHsX  \
reviews_username                                               
00dog3                             0.0                   0.0   
00sab00                            0.0                   0.0   
01impala                           0.0                   0.0   
02dakota                           0.0                   0.0   
02deuce                            0.0                   0.0   

id                AV1YmBrdGV-KLJ3adewb  AV1YmDL9vKc47QAVgr7_  \
reviews_username                                               
00dog3                             0.0                   0.0   
00sab00                            0.0                   0.0   
01impala                           0.0                   0.0   
02dakota                           0.0                   0.0   
02deuce                            0.0                   0.0   

id                AV1Ymf_rglJLPUi8II2v  AV1Yn94nvKc47QAVgtst  ...  \
reviews_username                                              ...   
00dog3                             0.0              0.000000  ...   
00sab00                            0.0              0.004400  ...   
01impala                           0.0              0.004260  ...   
02dakota                           0.0              0.007101  ...   
02deuce                            0.0              0.005680  ...   

id                AVpfrfHF1cnluZ0-pRai  AVpfrgjFLJeJML43BvCc  \
reviews_username                                               
00dog3                        0.000000                   0.0   
00sab00                       0.008822                   0.0   
01impala                      0.000000                   0.0   
02dakota                      0.000000                   0.0   
02deuce                       0.000000                   0.0   

id                AVpfs0tUilAPnD_xgqN2  AVpfsQoeilAPnD_xgfx5  \
reviews_username                                               
00dog3                             0.0                   0.0   
00sab00                            0.0                   0.0   
01impala                           0.0                   0.0   
02dakota                           0.0                   0.0   
02deuce                            0.0                   0.0   

id                AVpfshNsLJeJML43CB8q  AVpfthSailAPnD_xg3ON  \
reviews_username                                               
00dog3                             0.0              0.000000   
00sab00                            0.0              0.023175   
01impala                           0.0              0.000000   
02dakota                           0.0              0.000000   
02deuce                            0.0              0.000000   

id                AVpftikC1cnluZ0-p31V  AVpftymALJeJML43CZ6y  \
reviews_username                                               
00dog3                        0.000000                   0.0   
00sab00                       0.004475                   0.0   
01impala                      0.000000                   0.0   
02dakota                      0.000000               

### Finding the top 20 recommendation for the *user*



In [41]:
# Take the user ID as input
user_input = "laura"
print(user_input)

laura


In [42]:
# Recommending the Top 20 products to the user.
d = item_final_rating.loc[user_input].sort_values(ascending=False)[0:20]
d

id
AV1ZT7GLglJLPUi8IQLI    0.566389
AVpfE7puilAPnD_xUcCW    0.455286
AVpfkQkcLJeJML43_kEC    0.356089
AVpfOmKwLJeJML435GM7    0.212587
AVpfr5cb1cnluZ0-pZFp    0.208965
AVpfNc9cLJeJML434tza    0.194936
AVpfM_ytilAPnD_xXIJb    0.180636
AVpe5Mv4ilAPnD_xQQyy    0.156883
AVpe41TqilAPnD_xQH3d    0.119536
AVpe9W4D1cnluZ0-avf0    0.113605
AVpfrTyiLJeJML43BrSI    0.108725
AVpfRTh1ilAPnD_xYic2    0.092004
AVpf0pfrilAPnD_xi6s_    0.086800
AVpf4WWN1cnluZ0-s7Wj    0.080472
AVpfoSS51cnluZ0-oVH9    0.076966
AVpe8q4T1cnluZ0-afct    0.060943
AVpfR5m0LJeJML436K3W    0.055811
AVpfBU2S1cnluZ0-cJsO    0.055556
AVpfcu821cnluZ0-k8ep    0.051138
AVpe_5U_ilAPnD_xSrxG    0.049429
Name: laura, dtype: float64

# Loading the saved model from pkl file 

In [43]:
# Load the model from the file 
import joblib

sentiment_analysis = joblib.load('models/sentiment_analysis.pkl')
#sentiment_analysis = joblib.load('/content/gdrive/MyDrive/MyCapstone (1)/models/sentiment_analysis.pkl')

C:\Users\LPT-2347\anaconda3\lib\site-packages\sklearn\base.py:310: UserWarning: Trying to unpickle estimator LogisticRegression from version 0.22.2.post1 when using version 0.24.1. This might lead to breaking code or invalid results. Use at your own risk.
  warnings.warn(


In [44]:
from scipy.sparse import hstack
from sklearn.feature_extraction.text import TfidfVectorizer

In [45]:
## Replacing NAN values with blank from reviews_title field
df_org.reviews_title = df_org.reviews_title.fillna('')

In [46]:
all_text=df_org['reviews_title']+" "+df_org['reviews_text']

In [47]:
word_vectorizer = TfidfVectorizer(
    sublinear_tf=True,
    strip_accents='unicode',
    analyzer='word',
    token_pattern=r'\w{1,}',
    stop_words='english',
    ngram_range=(1, 1),
    max_features=10000)
word_vectorizer.fit(all_text)

TfidfVectorizer(max_features=10000, stop_words='english',
                strip_accents='unicode', sublinear_tf=True,
                token_pattern='\\w{1,}')

In [48]:
char_vectorizer = TfidfVectorizer(
    sublinear_tf=True,
    strip_accents='unicode',
    analyzer='char',
    stop_words='english',
    ngram_range=(2, 6),
    max_features=50000)
char_vectorizer.fit(all_text)

C:\Users\LPT-2347\anaconda3\lib\site-packages\sklearn\feature_extraction\text.py:502: UserWarning: The parameter 'stop_words' will not be used since 'analyzer' != 'word'
  warnings.warn("The parameter 'stop_words' will not be used"


TfidfVectorizer(analyzer='char', max_features=50000, ngram_range=(2, 6),
                stop_words='english', strip_accents='unicode',
                sublinear_tf=True)

# Getting the top 5 products for user recommendation out of 20

In [49]:
def getTopItemsFromModel(recommendItems) :
    resultDict = {}
    for id,predRating in recommendItems.items() :
        #print('index: ', id, 'value: ', predRating)
        item_text=df_org.reviews_text[df_org.id == id]
        train_word_features = word_vectorizer.transform(item_text)
        train_char_features = char_vectorizer.transform(item_text)
        item_features = hstack([train_char_features, train_word_features])
        result = sentiment_analysis.predict(item_features)
        #print("Item name",df_org.name[df_org.id == id][0:1])
        #print(len(result))
        positivePercent = round(((len(result[result == 'Positive'])/len(result))*100),2)
        #print("%age",positivePercent,"%")
        resultDict[id] = positivePercent
    return resultDict
  

In [50]:
def getItemsForUser(userName)  :
    print(userName)
    finalList = []
    #Handling for user not present in dataset
    if(userName not in df2['reviews_username'].tolist()) :
        return("User not found in dataset")
    items = item_final_rating.loc[userName].sort_values(ascending=False)[0:20]
    resultDict = getTopItemsFromModel(items)
    #print(resultDict)
    sorted_result = sorted(resultDict.items(), key=lambda x: x[1],reverse=True)
    print(sorted_result[0:5])
    for key,item in sorted_result[0:5] :
        finalList.append(df_org.name[df_org.id == key][0:1].values[0])
    return(finalList)

In [57]:
#outputList = getItemsForUser('laura')
#print("--------------")
#print(outputList)